// Catalog of all 10 Screenlytics Achievements

const ACHIEVEMENTS_CATALOG = [
  {
    key: 'streak_7',
    icon: '🔥',
    title: '7 Day Streak',
    description: 'Stay within your daily screen-time goal for 7 consecutive days.',
    targetValue: 7,
    unit: 'days',
    category: 'Streak',
  },
  {
    key: 'first_goal',
    icon: '🏅',
    title: 'First Goal Completed',
    description: 'Successfully complete your first daily screen-time goal.',
    targetValue: 1,
    unit: 'goal',
    category: 'Milestone',
  },
  {
    key: 'digital_detox',
    icon: '📵',
    title: 'Digital Detox',
    description: 'Complete a 2-hour distraction-free or focus session.',
    targetValue: 1,
    unit: 'session',
    category: 'Focus',
  },
  {
    key: 'under_4_hours',
    icon: '⏱️',
    title: 'Under 4 Hours',
    description: 'Keep your total screen time under 4 hours in a single day.',
    targetValue: 1,
    unit: 'day',
    category: 'Daily',
  },
  {
    key: 'early_wind_down',
    icon: '🌙',
    title: 'Early Wind-Down',
    description: 'Stay off your device after your configured evening wind-down time.',
    targetValue: 1,
    unit: 'night',
    category: 'Habits',
  },
  {
    key: 'streak_30',
    icon: '🔥',
    title: '30 Day Streak',
    description: 'Stay within your daily screen-time goal for 30 consecutive days.',
    targetValue: 30,
    unit: 'days',
    category: 'Streak',
  },
  {
    key: 'goal_crusher',
    icon: '🎯',
    title: 'Goal Crusher',
    description: 'Successfully complete your daily screen-time goal 10 times.',
    targetValue: 10,
    unit: 'goals',
    category: 'Milestone',
  },
  {
    key: 'screen_reducer',
    icon: '📉',
    title: 'Screen-Time Reducer',
    description: 'Decrease your total weekly screen time compared to the previous week.',
    targetValue: 1,
    unit: 'week',
    category: 'Progress',
  },
  {
    key: 'focus_master',
    icon: '🧘',
    title: 'Focus Master',
    description: 'Complete 10 distraction-free focus or study sessions.',
    targetValue: 10,
    unit: 'sessions',
    category: 'Focus',
  },
  {
    key: 'weekend_detox',
    icon: '📵',
    title: 'Weekend Detox',
    description: 'Stay below your screen-time target for both Saturday and Sunday.',
    targetValue: 1,
    unit: 'weekend',
    category: 'Special',
  },
];

module.exports = ACHIEVEMENTS_CATALOG;
